org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=TestMod
modName=Test Mod
modGroup=mods.test
modid=testmod
author=TestMan
desc=A Test mod
version=1.0.0

# Dependencies
mcVersion=1.21.1
javaVersion=21
forgeVersion=21.1.187
parchmentVersion=2024.11.17-1.21.1
jeiVersion=19.21.2.313
jadeVersion=15.10.2
placeboVersion=9.9.0
#curiosVersion=9.5.1+1.21.1
#patchouliVersion=1.19.2-76

# Mixins
mixin=false
mixinVersion=0.8.7

# Publishing
#requiredDeps=
#optionalDeps=
#incompatibleDeps=
#releaseType=beta
#modLoaders=NeoForge
#curseforgeProjectId=

# Tests
enableTests=false
